services:
  web:
    build:
      context: webapp
      dockerfile: Dockerfile
    ports:
      - "8080:80"

  database:
    build:
      context: database
      dockerfile: Dockerfile
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=movie123
